#!/bin/sh

[ -d flatpak-builder-tools ] || git clone https://github.com/flatpak/flatpak-builder-tools.git
git -C flatpak-builder-tools pull
wget https://github.com/qutebrowser/qutebrowser/raw/v2.1.0/requirements.txt -O requirements.txt

flatpak run --command=sh --share=network --filesystem=$PWD org.kde.Sdk//5.15 -c '\
  pip3 install --user requirements-parser
    flatpak-builder-tools/pip/flatpak-pip-generator \
      -r requirements.txt \
      -o pypi-dependencies
'
